DROP ROLE IF EXISTS 'SUPERUSUARIO';
DROP ROLE IF EXISTS 'SUPERVISOR';
DROP ROLE IF EXISTS 'GUARDA';
DROP ROLE IF EXISTS 'FUNCIONARIO';

-- CREACION DE ROLES CON SUS PERMISOS A TABLAS
CREATE ROLE 'SUPERUSUARIO';

GRANT ALL PRIVILEGES ON complejoacme.* TO 'SUPERUSUARIO';

CREATE ROLE 'SUPERVISOR';

GRANT SELECT, INSERT, UPDATE ON complejoacme.personal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.restricciones TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.restriccionespersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.incidentes TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.incidentespersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.permisosvisitantes TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.controlaccesospersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.vehiculo TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.controlaccesosvehicular TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.empresaspersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.empresas TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.logregistros TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getpersonal TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getempresapersonal TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getcapersonal TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getlogregistros TO 'SUPERVISOR';


CREATE ROLE 'GUARDA';

GRANT SELECT, INSERT, UPDATE ON complejoacme.controlaccesospersonal TO 'GUARDA';
GRANT SELECT, INSERT, UPDATE ON complejoacme.vehiculo TO 'GUARDA';
GRANT SELECT, INSERT, UPDATE ON complejoacme.controlaccesosvehicular TO 'GUARDA';
GRANT EXECUTE ON PROCEDURE getvehiculos TO 'GUARDA';
GRANT EXECUTE ON PROCEDURE getcavehiculo TO 'GUARDA';
GRANT EXECUTE ON PROCEDURE getcapersonal TO 'GUARDA';


GRANT INSERT ON complejoacme.incidentespersonal TO 'GUARDA';

CREATE ROLE 'FUNCIONARIO';

GRANT SELECT, INSERT, UPDATE ON complejoacme.personal TO 'FUNCIONARIO';
GRANT SELECT, INSERT, UPDATE ON complejoacme.permisosvisitantes TO 'FUNCIONARIO';
GRANT SELECT, INSERT, UPDATE ON complejoacme.empresaspersonal TO 'FUNCIONARIO';
GRANT EXECUTE ON PROCEDURE getpersonal TO 'FUNCIONARIO';
GRANT EXECUTE ON PROCEDURE getempresapersonal TO 'FUNCIONARIO';

-- CREACION DE USUARIOS DE PRUEBA

DROP USER IF EXISTS 'superusuario1'@'127.0.0.1';
CREATE USER 'superusuario1'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS 'supervisor1'@'127.0.0.1';
CREATE USER 'supervisor1'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS 'guarda1'@'127.0.0.1';
CREATE USER 'guarda1'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS 'funcionario1'@'127.0.0.1';
CREATE USER 'funcionario1'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";

DROP USER IF EXISTS 'supervisor2'@'127.0.0.1';
CREATE USER 'supervisor2'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS 'guarda2'@'127.0.0.1';
CREATE USER 'guarda2'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS 'funcionario2'@'127.0.0.1';
CREATE USER 'funcionario2'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";

DROP USER IF EXISTS 'supervisor3'@'127.0.0.1';
CREATE USER 'supervisor3'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS 'guarda3'@'127.0.0.1';
CREATE USER 'guarda3'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS 'funcionario3'@'127.0.0.1';
CREATE USER 'funcionario3'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";

-- AGREGAR LOS ROLES A LOS USUARIOS DE PRUEVA
GRANT 'SUPERUSUARIO' TO 'superusuario1'@'127.0.0.1';
GRANT 'SUPERVISOR' TO 'supervisor1'@'127.0.0.1';
GRANT 'GUARDA' TO 'guarda1'@'127.0.0.1';
GRANT 'FUNCIONARIO' TO 'funcionario1'@'127.0.0.1';
GRANT 'SUPERVISOR' TO 'supervisor2'@'127.0.0.1';
GRANT 'GUARDA' TO 'guarda2'@'127.0.0.1';
GRANT 'FUNCIONARIO' TO 'funcionario2'@'127.0.0.1';
GRANT 'SUPERVISOR' TO 'supervisor3'@'127.0.0.1';
GRANT 'GUARDA' TO 'guarda3'@'127.0.0.1';
GRANT 'FUNCIONARIO' TO 'funcionario3'@'127.0.0.1';

-- APLICAR LOS ROLES
SET DEFAULT ROLE ALL TO 'superusuario1'@'127.0.0.1';
SET DEFAULT ROLE ALL TO 'supervisor1'@'127.0.0.1';
SET DEFAULT ROLE ALL TO 'guarda1'@'127.0.0.1';
SET DEFAULT ROLE ALL TO 'funcionario1'@'127.0.0.1';

SET DEFAULT ROLE ALL TO 'supervisor2'@'127.0.0.1';
SET DEFAULT ROLE ALL TO 'guarda2'@'127.0.0.1';
SET DEFAULT ROLE ALL TO 'funcionario2'@'127.0.0.1';

SET DEFAULT ROLE ALL TO 'supervisor3'@'127.0.0.1';
SET DEFAULT ROLE ALL TO 'guarda3'@'127.0.0.1';
SET DEFAULT ROLE ALL TO 'funcionario3'@'127.0.0.1';