DROP ROLE IF EXISTS 'SUPERUSUARIO';
DROP ROLE IF EXISTS 'SUPERVISOR';
DROP ROLE IF EXISTS 'GUARDA';
DROP ROLE IF EXISTS 'FUNCIONARIO';

-- CREACION DE ROLES CON SUS PERMISOS A TABLAS
CREATE ROLE 'SUPERUSUARIO';

GRANT ALL PRIVILEGES ON complejoacme.* TO 'SUPERUSUARIO';

CREATE ROLE 'SUPERVISOR';

GRANT SELECT, INSERT, UPDATE ON complejoacme.personal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.restricciones TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.restriccionespersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.incidentes TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.incidentespersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.permisosvisitantes TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.controlaccesospersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.vehiculo TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.controlaccesosvehicular TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.empresaspersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.empresas TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.logregistros TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.logcambioestado TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON complejoacme.rol TO 'SUPERVISOR';
GRANT CREATE USER ON *.* TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getpersonal TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getvehiculos TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getcavehiculo TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getempresapersonal TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getcapersonal TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getlogregistros TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getpermisosvisitantes TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getrestriccionespersonal TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getlogcambioestado TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE getincidentespersonal TO 'SUPERVISOR';
GRANT EXECUTE ON PROCEDURE creausuario TO 'SUPERVISOR';


CREATE ROLE 'GUARDA';

GRANT SELECT, INSERT, UPDATE ON complejoacme.controlaccesospersonal TO 'GUARDA';
GRANT SELECT, INSERT, UPDATE ON complejoacme.vehiculo TO 'GUARDA';
GRANT SELECT, INSERT, UPDATE ON complejoacme.controlaccesosvehicular TO 'GUARDA';
GRANT INSERT, INSERT, UPDATE ON complejoacme.incidentespersonal TO 'GUARDA';
GRANT SELECT ON complejoacme.empresas TO 'GUARDA';
GRANT SELECT ON complejoacme.incidentes TO 'GUARDA';
GRANT SELECT ON complejoacme.restricciones TO 'GUARDA';
GRANT EXECUTE ON PROCEDURE getvehiculos TO 'GUARDA';
GRANT EXECUTE ON PROCEDURE getcavehiculo TO 'GUARDA';
GRANT EXECUTE ON PROCEDURE getcapersonal TO 'GUARDA';
GRANT EXECUTE ON PROCEDURE getincidentespersonal TO 'GUARDA';

GRANT EXECUTE ON PROCEDURE creausuario TO 'GUARDA';



CREATE ROLE 'FUNCIONARIO';

GRANT SELECT, INSERT, UPDATE ON complejoacme.personal TO 'FUNCIONARIO';
GRANT SELECT, INSERT, UPDATE ON complejoacme.permisosvisitantes TO 'FUNCIONARIO';
GRANT SELECT, INSERT, UPDATE ON complejoacme.empresaspersonal TO 'FUNCIONARIO';
GRANT SELECT, INSERT, UPDATE ON complejoacme.rol TO 'FUNCIONARIO';
GRANT SELECT, INSERT, UPDATE ON complejoacme.empresas TO 'FUNCIONARIO';
GRANT SELECT, INSERT, UPDATE ON complejoacme.vehiculo TO 'FUNCIONARIO';
GRANT CREATE USER ON *.* TO 'FUNCIONARIO';
GRANT EXECUTE ON PROCEDURE getpersonal TO 'FUNCIONARIO';
GRANT EXECUTE ON PROCEDURE getcapersonal TO 'FUNCIONARIO';
GRANT EXECUTE ON PROCEDURE getempresapersonal TO 'FUNCIONARIO';
GRANT EXECUTE ON PROCEDURE getpermisosvisitantes TO 'FUNCIONARIO';

-- CREACION DE USUARIOS DE PRUEBA

DROP USER IF EXISTS 's'@'%';
CREATE USER 's'@'%' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS '1'@'%';
CREATE USER '1'@'%' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS '2'@'%';
CREATE USER '2'@'%' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS '3'@'%';
CREATE USER '3'@'%' IDENTIFIED BY "QwEr_12@";
-- AGREGAR LOS ROLES A LOS USUARIOS DE PRUEVA
GRANT 'SUPERUSUARIO' TO 's'@'%';
GRANT 'SUPERVISOR' TO '1'@'%';
GRANT 'GUARDA' TO '2'@'%';
GRANT 'FUNCIONARIO' TO '3'@'%';

-- APLICAR LOS ROLES
SET DEFAULT ROLE ALL TO 's'@'%';
SET DEFAULT ROLE ALL TO '1'@'%';
SET DEFAULT ROLE ALL TO '2'@'%';
SET DEFAULT ROLE ALL TO '3'@'%';