DROP ROLE IF EXISTS 'SUPERUSUARIO';
DROP ROLE IF EXISTS 'SUPERVISOR';
DROP ROLE IF EXISTS 'GUARDA';
DROP ROLE IF EXISTS 'FUNCIONARIO';

-- CREACION DE ROLES CON SUS PERMISOS A TABLAS
CREATE ROLE 'SUPERUSUARIO';

GRANT ALL PRIVILEGES ON ComplejoACME.* TO 'SUPERUSUARIO';

CREATE ROLE 'SUPERVISOR';

GRANT SELECT, INSERT, UPDATE ON ComplejoACME.Personal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.Restricciones TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.RestriccionesPersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.Incidentes TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.IncidentesPersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.PermisosVisitantes TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.ControlAccesosPersonal TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.Vehiculo TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.ControlAccesosVehicular TO 'SUPERVISOR';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.EmpresasPersonal TO 'SUPERVISOR';


CREATE ROLE 'GUARDA';

GRANT SELECT, INSERT, UPDATE ON ComplejoACME.ControlAccesosPersonal TO 'GUARDA';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.Vehiculo TO 'GUARDA';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.ControlAccesosVehicular TO 'GUARDA';


GRANT INSERT ON ComplejoACME.IncidentesPersonal TO 'GUARDA';

CREATE ROLE 'FUNCIONARIO';

GRANT SELECT, INSERT, UPDATE ON ComplejoACME.Personal TO 'FUNCIONARIO';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.PermisosVisitantes TO 'FUNCIONARIO';
GRANT SELECT, INSERT, UPDATE ON ComplejoACME.EmpresasPersonal TO 'FUNCIONARIO';


-- CREACION DE USUARIOS DE PRUEBA CON SUS ROLES


DROP USER IF EXISTS 'superusuario1'@'127.0.0.1';
CREATE USER 'superusuario1'@'127.0.0.1' IDENTIFIED BY "QwEr_12@";
DROP USER IF EXISTS 'supervisor1'@'127.0.0.1';
CREATE USER 'supervisor1'@'127.0.0.1';
DROP USER IF EXISTS 'guarda1'@'127.0.0.1';
CREATE USER 'guarda1'@'127.0.0.1';
DROP USER IF EXISTS 'funcionario1'@'127.0.0.1';
CREATE USER 'funcionario1'@'127.0.0.1';

GRANT 'SUPERUSUARIO' TO 'superusuario1'@'127.0.0.1';
GRANT 'SUPERVISOR' TO 'supervisor1'@'127.0.0.1';
GRANT 'GUARDA' TO 'guarda1'@'127.0.0.1';
GRANT 'FUNCIONARIO' TO 'funcionario1'@'127.0.0.1';

SET DEFAULT ROLE ALL TO 'superusuario1'@'127.0.0.1';
SET DEFAULT ROLE ALL TO 'supervisor1'@'127.0.0.1';
SET DEFAULT ROLE ALL TO 'guarda1'@'127.0.0.1';
SET DEFAULT ROLE ALL TO 'funcionario1'@'127.0.0.1';